Name = "LowEntropy"

Hosts = [
    "http://example.tld/",
    "https://example.tld/"
]

Listen = "http://localhost:8080"

[Notify.Log]
Enable = true
FilePath = ""

[Notify.Email]
Enable = true
CanReplyNotifications = true
To = "your@email.tld"
From = '"Foo Bar" <isso@example.tld>'
    [Notify.Email.Smtp]
    Username = ""
    Password = ""
    Host = ""
    Port = ""
    Security = ""
    Timeout = 10

[Notify.Telegram]
Enable = false
UserID = 9090900

[Database.Sqlite]
    Path = "./comments.db"

[Admin]
Enable = true
Password = "please_choose_a_strong_password"

[Moderation]
Enable = true
PurgeAfter = "30d"

[Guard]
Enable = true
# API limit
RateLimit = 2
EditMaxAge = "15m"
# database limit
DirectReply = 3
ReplyToSelf = true
RequireAuthor = true
RequireEmail = true

[Markup]
Options = ["strikethrough", "autolink", "fenced_code"]
AdditionalAllowedElements = [""]
AdditionalAllowedAttributes = [""]

[Hash]
Salt = ""
Algorithm = ""